### ISSUE TITLE
hi,can you tell me how to repack?

### ISSUE THREAD

**Issue by DogUoUo** [RedMadKnight/D3CPKUnpack#1]
in 2020, i happy look you still make this tool for xbox360.
but i want translate this game, and i find in google had chinese ver.
and use your tool, but can't unpack this chinese ver: enUS_Common.cpk.
by the way, your tool isn't unpack all file from original game file: enUS_Common.cpk.
i think maybe it's file size more than 1MB?
and i use Beyond Compare 4, it say chinese ver different file is Common.cpk, enUS_CacheCommon.cpk, enUS_Common.cpk

so~
my english isn't good.
my c# just learn a little, but i really want to do that things...
i wish want get your help to do it fast.
please, thanks a lot...

**Comment by DogUoUo** [comment]
i upload that file to mega:
https://mega.nz/folder/XJ1REIwI#LJuJBMTI8JFaRIvvhSS-jg
CHS_* is chinese ver files.

**Comment by RedMadKnight** [comment]
Hi - this tool is not ready.
It is possible to unpack some of the files by analyzing Locations and SortedFileInfo, to find the correct chunck in the Sector.
